dev-env/src/__init__.py
#Alexander Shelton
#Holds the function that is called in run.py

import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
#Configuration File: src/config.py
from src.config import Config



# #Creating db instance, called back in model.py
db = SQLAlchemy()



def create_app():
    app = Flask(__name__)
    app.config.from_object(Config) #Configuring FlaskApp from config.py file. allows multiple instances
    db.init_app(app)


    #Importing blueprint instances
    from src.main.routes import main
    from src.data.routes import data

    #registering blueprints
    app.register_blueprint(main)
    app.register_blueprint(data)

    return app

dev-env/src/data/routes.py
# Alex Shelton
# Routes.py : handles all routing that has to do with showing/manipulating data
# For files that show graphing OR tableview or sql data
#


from flask import render_template, request, Blueprint, flash, redirect, url_for
from src import db
from src.model import graph_data

from datetime import datetime, date
# querying
import sqlite3
from sqlite3 import Error
from src.data import dbtools



# db_path = "/Users/alexshelton/Desktop/Flask-Util-App/dev-env/src/data.sqlite"
db_path = dbtools.db_path



#Creating a blueprint instance
data = Blueprint('data', __name__)

@data.route('/tableview',methods=['GET', 'POST'])
def tableview():
    THISWEEK = date.today().isocalendar()[1] #Number of the current week number ex: jan 1st would return '1'

    if request.method == 'POST':
        try:
            selected_week =  int(request.form.get('week'))
        except ValueError:
            flash("Invalid Value", "failure")
            return redirect(url_for('data.tableview'))

        #Checking bounds weeks are 1-52:
        if selected_week > 52 or selected_week < 0:
            flash("invalid")
            pass# Leave if statement logic: show current weeks table

        #IF week is 0: web page loads whole table
        elif selected_week == 0:
            alldata = dbtools.returnTable()
            return render_template('tableview.html', data=alldata, week=THISWEEK)

        #else load week:
        else:
            weekdata = dbtools.returnWeeklyTable(selected_week)
            return render_template('tableview.html', data=weekdata, week=THISWEEK)

    #Code executes if inputted week was > 52 or < 0:
    current_week = dbtools.returnWeeklyTable(THISWEEK)
    return render_template('tableview.html', data=current_week, week=THISWEEK)





@data.route('/weekdata')
def weekdata():
    # grab current week number
    # returnWeeklySums returns an array with totals for mon-fri. size n = 7

    THISWEEK = date.today().isocalendar()[1] #Number of the current week number ex: jan 1st would return '1'
    weekly_data = dbtools.returnWeeklySums(THISWEEK)
    legend = 'Weekly Data'
    labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    return render_template('weekdata.html', values=weekly_data, labels=labels, legend=legend)




@data.route('/summary_data')
def summary_data():
    # grab current week number
    # returnWeeklySums returns an array with totals for mon-fri. size n = 7
    # return n = 52 size array with sums of every week

    THISWEEK = date.today().isocalendar()[1] #Number of the current week number ex: jan 1st would return '1'
    LASTWEEK = THISWEEK -1
    weekly_data = dbtools.returnWeeklySums(LASTWEEK)
    all_weeks_data = dbtools.return52weeks()
    labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    return render_template('summary_data.html', labels= labels, values=weekly_data, plot_data = all_weeks_data)

dev-env/src/main/routes.py
#Alexander Shelton
#Main content routing of webapp

from flask import render_template, request, Blueprint, flash, redirect, url_for
from src import db
from src.model import graph_data

from datetime import datetime

# querying
import sqlite3
from sqlite3 import Error



#Creating a blueprint instance
main = Blueprint('main', __name__)



@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html')


@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/<int:time>')
def enter(time):
    try: #converting num to string or chekcing if it is  astring. If it is not a string, value err, wont commit to db
        int_time = int(time)
        data = graph_data(time_spent=int_time)
        db.session.add(data)
        db.session.commit()
     
        return redirect(url_for('main.home'))

    except ValueError as e:
        print(e)
        return render_template("about.html")

dev-env/src/templates/about.html
{% extends "layout.html" %}
{% block content %}

  <div class="about-wrapper">
    <div class="about-inside">

      <h1>About this site</h1>
    <p>
        Website is built using the Flask framework <br />
        HTML/CCS design is Bootstrap <br />
        Graphing done with Charts.js
    </p>
    </div>
  </div>
{% endblock %}

dev-env/src/templates/data.html
{% extends "layout.html" %}
{% block content %}
    <h1>Data</h1>
    <p>
        This is where all past data will be
    </p>

    <main role="main" class="container">

  <div class="line-graph">
  <div class="row">
  <center>
  <canvas id="line-chart" width="800" height="450"></canvas>

    <script type="text/javascript">
    // creating an array with numbers 1-52 for weeks of the year
    let label_array = [];
    for (let i = 1; i < 53; i++){
      label_array.push(i);
    }

    let dataplot = [];
    for (let i = 1; i < 52; i++){
      let num = Math.floor(Math.random() * 100)
      dataplot.push(num);
    }

      new Chart(document.getElementById("line-chart"), {
        type: 'line',
        data: {
          labels: label_array,
          datasets: [{
              data:dataplot, //[282,350,411,502,635,809,947,1402,3700,5267],
              label: "Time spent (min)",
              borderColor: "#8e5ea2",
              fill: false
            }
          ]
        },
        options: {
          legend: {
            display: false
          },
          title: {
            display: true,
            text: 'Monthly Time Raspberry Pi logging',
            fontColor: "#ffffff"
          },
          scales:{
            yAxes: [{
              scaleLabel: {
                display: true,
                labelString: "Minutes",
                fontColor: "#ffffff"
              },
              ticks: {
                beginAtZero: true,
                fontColor: "#ffffff"
              }
            }],
          xAxes: [{
            scaleLabel: {
              display: true,
              labelString: "Months of the year",
              fontColor: "#ffffff"
            },
            ticks: {
              fontColor: "#ffffff"
            }
          }]
          }
        }
      });

    </script>
    </center>
    </div>
      </div>
      </main>

{% endblock %}

dev-env/src/templates/home.html
{% extends "layout.html" %}
{% block content %}

  <h1>This is the new home page</h1>



{% endblock %}

dev-env/src/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
       <!-- Required meta tags -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Charts.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- <meta charset="utf-8"> -->
    <meta charset="utf-8"/>
  </head>
  <body>
<header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <a class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com/in/alexander-shelton-codes/">
                    <span class="fa fa-linkedin"></span>
                </a>
                <a class="btn btn-social-icon btn-github" href="https://www.github.com/alexshelto/">
                    <span class="fa fa-github"></span>
                </a>
                <a class="btn btn-brand btn-youtube" href="https://www.youtube.com/channel/UCNm_1qvIVDRwbeyikyCXOIg/videos?view=">
                    <span class="fa fa-youtube"></span>
                </a>
            <div class="container">
            <a class="navbar-brand mr-4" href="/">Alex's Utility Site</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{{url_for('data.weekdata')}}">This Week</a>
                <a class="nav-item nav-link" href="{{url_for('data.summary_data')}}" >Past Data</a>
                <a class="nav-item nav-link" href="{{url_for('data.tableview') }}">Table View</a>
                <a class="nav-item nav-link" href="{{url_for('main.about')}}">About site</a>
                <!--- add in a if user is authenticated for python browser programming-->
                </div>
            </div>
            </div>
        </nav>
        </header>
    <main role="main" class="container">
            <!-- <div class="row"> -->
                <div class="col-md-8">

                {% block content %}{% endblock %}
                </div>
            <!-- </div> -->
            </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

dev-env/src/templates/summary_data.html
{% extends "layout.html" %}
{% block content %}



    <main role="main" class="container">

      <div class="line-graph">
        <div class="row">

          <center>
            <canvas id="pie-chart" width="800" height="450"></canvas>
              <script type="text/javascript">
                pieData = {
                labels : [
                    {% for item in labels %}
                      "{{ item }}",
                    {% endfor %}
                  ],
                  data : [
                          {% for item in values %}
                            "{{ item }}",
                            {% endfor %} ]
                }


              new Chart(document.getElementById("pie-chart"), {
                type: 'pie',
                data: {
                  labels: pieData.labels,
                  datasets: [{
                    label: "Time spent (minutes)",
                    backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850", "#ff0", "#f02e85"],
                    data: pieData.data
                  }]
                },
                options: {
                  cutoutPercentage: 40,
                  legend: {
                    labels:{
                      fontColor: "#ffffff",
                      fontSize: 12,

                    }
                  },
                  title: {
                    display: true,
                    text: 'Last weeks time breakdown (min)',
                    fontColor: "#ffffff"
                  }
                }
              });

            </script>
        </center>
        </div>
    </div>

    <div class="gap"></div>

  <div class="line-graph">
  <div class="row">
  <center>
  <canvas id="line-chart" width="800" height="450"></canvas>

    <script type="text/javascript">
    // creating an array with numbers 1-52 for weeks of the year
    let label_array = [];
    for (let i = 1; i < 53; i++){
      label_array.push(i);
    }

    dataplot = [
    {% for item in plot_data %}
      "{{ item }}",
    {% endfor %}
    ]

      new Chart(document.getElementById("line-chart"), {
        type: 'line',
        data: {
          labels: label_array,
          datasets: [{
              data:dataplot, //[282,350,411,502,635,809,947,1402,3700,5267],
              label: "Time spent (min)",
              borderColor: "#7d0aad",
              fill: false
            }
          ]
        },
        options: {
          legend: {
            display: false
          },
          title: {
            display: true,
            text: 'Monthly Time Raspberry Pi logging',
            fontColor: "#ffffff"
          },
          scales:{
            yAxes: [{
              scaleLabel: {
                display: true,
                labelString: "Minutes",
                fontColor: "#ffffff"
              },
              ticks: {
                beginAtZero: true,
                fontColor: "#ffffff"
              }
            }],
          xAxes: [{
            scaleLabel: {
              display: true,
              labelString: "Months of the year",
              fontColor: "#ffffff"
            },
            ticks: {
              fontColor: "#ffffff"
            }
          }]
          }
        }
      });

    </script>
    </center>
    </div>
      </div>




      </main>

{% endblock %}

dev-env/src/templates/tableview.html
{% extends "layout.html" %}

  {% block content %}
  <div class="week-input">

    <h2> Current week number: {{week}} </h2>
    <form class="week-entry" action='/tableview' method="post">
      <input type="text" name="week" week number>
       <input type="submit" value="Submit">
    </form>


  </div>


  <table class="data-table">
    <tr>
      <th class="data-th">ID</th>
      <th class="data-th">Week</th>
      <th class="data-th">Day</th>
      <th class="data-th">Time Spent(min)</th>
      <th class="data-th">Time Stamp</th>
    </tr>

    {% for i,w,d,t,tt  in data %}

        <tr class="table-tr">
                <td class="data-td">{{ i }}</td>
                <td class="data-td">{{ w }}</td>
                <td class="data-td">{{ d }}</td>
                <td class="data-td">{{ t }}</td>
                <td class="data-td">{{ tt }}</td>
        </tr>
    {% endfor %}
  </table>

{% endblock %}

dev-env/src/templates/weekdata.html
{% extends "layout.html" %}
{% block content %}


<div class="graph-container">

  <div class="line-graph">

    <canvas id="chart" width="800" height="450"></canvas>
    <script>


    barData = {
    labels : [
         {% for item in labels %}
          "{{ item }}",
         {% endfor %}
       ],
       data : [
              {% for item in values %}
                 "{{ item }}",
                {% endfor %} ]
     }

    // Bar chart
    new Chart(document.getElementById("chart"), {
      type: 'bar',
      data: {
        labels: barData.labels,
        datasets: [
          {
            label: "Time (minutes)",
            backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850", "#ff0", "#f02e85"],
            data: barData.data
          }
        ]
      },
      options: {
        legend: {
          display: false
        },
        title: {
          display: true,
          text: 'Raspberry PI LED time on',
          fontColor: "#FFFFFF"
        },
        responsive: true,
        scales: {
          yAxes: [{
            scaleLabel: {
              display: true,
              labelString: "Minutes",
              fontColor: "#FFFFFF"
            },
            ticks: {
              beginAtZero: true,
              fontColor: "#ffffff"
            }
          }],
        xAxes: [{
          scaleLabel: {
            display: true,
            labelString: "Days of the week",
            fontColor: "#FFFFFF"
          },
          ticks: {
            fontColor: "#ffffff"
          }}]
        }
      }
    });

</script>

</div>
</div>







{% endblock %}